# # see: https://terraform-docs.io/user-guide/configuration/version
# version: ">= 0.10, < 0.12"

# see: https://terraform-docs.io/user-guide/configuration/formatter
formatter: markdown table

content: |2-

  ## Usage

  1. Get the Harvester kubeconfig and place it in `harvester.kubeconfig`
  1. Adapt the config
  1. Configure Harvester with `terraform apply`


  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}

# see: https://terraform-docs.io/user-guide/configuration/sort
sort:
  enabled: true
  by: name

# see: https://terraform-docs.io/user-guide/configuration/settings
settings:
  indent: 4
  escape: false
  default: false
  required: false
  type: true
